### ISSUE TITLE
希望可以新增國際版、印度版的適配

### ISSUE THREAD

**Issue by k2913064** [Xposed-Modules-Repo/com.oosl.colorostool#1]
作者您好
謝謝您開發那麼方便的模組
之前陸版確實可以正常使用
但換到國際版沒有作用
希望可以新增支援國際版及印度版
謝謝您😀

**Comment by k2913064** [comment]
作者好
1.8.8版本
120hz開關開啟再關掉，還是強制120hz無法切回60hz

**Comment by Oosl** [comment]
> 作者您好 謝謝您開發那麼方便的模組 之前陸版確實可以正常使用 但換到國際版沒有作用 希望可以新增支援國際版及印度版 謝謝您😀

由于我没有相应系统的手机，所以很抱歉适配不了

**Comment by Oosl** [comment]
> 作者好 1.8.8版本 120hz開關開啟再關掉，還是強制120hz無法切回60hz

开关只是作用于进入”设置-显示-刷新率“界面时，是否执行强制120hz的相关代码，切换开关并不会实时切换系统刷新率。如需切回60，在”设置-显示-刷新率“使用系统设置对应状态即可。
